[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/sudoku-solver"
  to = "/sudoku-solver.html"
  status = 200

[[redirects]]
  from = "/simplex-noise"
  to = "/simplex-noise.html"
  status = 200
